debugging-five/gradation-back

src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/java/com/app/gradationback/domain/CommentVO.java
src/main/java/com/app/gradationback/domain/UserVO.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java
src/test/java/com/app/gradationback/mapper/mina/DisplayMapperTests.java
src/test/java/com/app/gradationback/mapper/mina/UserMapperTests.java

feat: userAPI 완료

---

src/main/resources/config/config.xml

feat: config 수정

---

src/main/java/com/app/gradationback/controller/FaqController.java
src/main/java/com/app/gradationback/controller/MailController.java
src/main/java/com/app/gradationback/repository/FaqDAO.java
src/main/java/com/app/gradationback/repository/MailDAO.java
src/main/java/com/app/gradationback/service/FaqService.java
src/main/java/com/app/gradationback/service/FaqServiceImpl.java
src/main/java/com/app/gradationback/service/MailService.java
src/main/java/com/app/gradationback/service/MailServiceImpl.java

feat: faq 백완료

---

src/test/java/com/app/gradationback/mapper/mina/CommentMapperTests.java

feat: CommentMapperTests 수정

---

src/main/resources/mapper/exhibitionMapper.xml

feat: exhibition 수정

---

src/main/java/com/app/gradationback/config/SecurityConfig.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/resources/mapper/userMapper.xml

feat: SecurityConfig 작업 중

---

src/main/java/com/app/gradationback/config/SecurityConfig.java
src/main/java/com/app/gradationback/controller/AuthController.java
src/main/java/com/app/gradationback/service/SmsService.java
src/main/java/com/app/gradationback/util/SmsUtil.java

feat: SecurityConfig 추가

---

src/main/java/com/app/gradationback/config/SecurityConfig.java
src/main/java/com/app/gradationback/controller/AuthController.java
src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/java/com/app/gradationback/mapper/ArtPostMapper.java
src/main/java/com/app/gradationback/mapper/UserMapper.java
src/main/java/com/app/gradationback/repository/ArtPostDAO.java
src/main/java/com/app/gradationback/repository/UserDAO.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/java/com/app/gradationback/service/UserService.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java
src/main/java/com/app/gradationback/util/JwtTokenUtil.java
src/main/resources/mapper/artPostMapper.xml
src/main/resources/mapper/userMapper.xml
src/test/java/com/app/gradationback/mapper/mina/ArtMapperTests.java
src/test/java/com/app/gradationback/mapper/mina/ArtPostMapperTests.java
src/test/java/com/app/gradationback/mapper/mina/UserMapperTests.java

feat: UserController 수정

---

src/main/java/com/app/gradationback/controller/UserController.java
src/test/java/com/app/gradationback/mapper/mina/UserMapperTests.java

feat: 이메일 중복 검사 추가

---

src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/mapper/ArtMapper.java
src/main/java/com/app/gradationback/repository/ArtDAO.java
src/main/java/com/app/gradationback/service/ArtLikeService.java
src/main/java/com/app/gradationback/service/ArtLikeServiceImpl.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/resources/mapper/artMapper.xml
src/test/java/com/app/gradationback/mapper/mina/ArtLikeMapperTests.java

feat: LikeAPI 추가

---

src/main/java/com/app/gradationback/controller/ArtLikeController.java
src/main/java/com/app/gradationback/controller/DisplayController.java

feat: ArtLikeAPI 추가

---

src/main/java/com/app/gradationback/controller/MailController.java
src/main/java/com/app/gradationback/controller/QnaController.java
src/main/java/com/app/gradationback/mapper/MailMapper.java
src/main/java/com/app/gradationback/repository/MailDAO.java
src/main/java/com/app/gradationback/service/MailService.java
src/main/java/com/app/gradationback/service/MailServiceImpl.java
src/main/resources/mapper/mailMapper.xml
src/test/java/com/app/gradationback/mapper/seungmin/MailMapperTests.java

feat: mail 백 완료

---

src/main/java/com/app/gradationback/controller/MailController.java
src/main/java/com/app/gradationback/mapper/MailMapper.java
src/main/java/com/app/gradationback/repository/MailDAO.java
src/main/java/com/app/gradationback/service/MailService.java
src/main/java/com/app/gradationback/service/MailServiceImpl.java
src/main/resources/mapper/mailMapper.xml
src/main/resources/mapper/qnaMapper.xml
src/test/java/com/app/gradationback/mapper/seungmin/MailMapperTests.java

feat: Mail서비스 수정

---

src/main/java/com/app/gradationback/controller/QnaController.java
src/main/java/com/app/gradationback/service/QnaService.java
src/main/java/com/app/gradationback/service/QnaServiceImpl.java
src/main/resources/mapper/mailMapper.xml

"feat: MailMapper, QnaController 수정

feat: MailMapper, QnaController 수정

---

src/main/java/com/app/gradationback/controller/CommentController.java
src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/domain/ArtPostDTO.java
src/main/java/com/app/gradationback/mapper/ArtImgMapper.java
src/main/java/com/app/gradationback/mapper/ArtMapper.java
src/main/java/com/app/gradationback/mapper/ArtPostMapper.java
src/main/java/com/app/gradationback/mapper/CommentMapper.java
src/main/java/com/app/gradationback/repository/ArtDAO.java
src/main/java/com/app/gradationback/repository/ArtImgDAO.java
src/main/java/com/app/gradationback/repository/ArtPostDAO.java
src/main/java/com/app/gradationback/repository/CommentDAO.java
src/main/java/com/app/gradationback/service/ArtImgService.java
src/main/java/com/app/gradationback/service/ArtImgServiceImpl.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/java/com/app/gradationback/service/ArtService.java
src/main/java/com/app/gradationback/service/ArtServiceImpl.java
src/main/java/com/app/gradationback/service/CommentService.java
src/main/java/com/app/gradationback/service/CommentServiceImpl.java
src/main/resources/mapper/artImgMapper.xml
src/main/resources/mapper/artMapper.xml
src/main/resources/mapper/artPostMapper.xml
src/main/resources/mapper/commentMapper.xml
src/test/java/com/app/gradationback/mapper/mina/ArtImgMapperTests.java
src/test/java/com/app/gradationback/mapper/mina/ArtMapperTests.java

feat: CommentAPI, DisplayAPI 추가

---

src/main/java/com/app/gradationback/config/SecurityConfig.java
src/main/java/com/app/gradationback/controller/AuthController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/java/com/app/gradationback/mapper/UserMapper.java
src/main/java/com/app/gradationback/repository/UserDAO.java
src/main/java/com/app/gradationback/service/UserService.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java
src/main/resources/mapper/userMapper.xml

feat: 이메일 전소 오류 수정

---

src/main/java/com/app/gradationback/mapper/ArtMapper.java
src/main/java/com/app/gradationback/repository/ArtDAO.java
src/main/java/com/app/gradationback/service/ArtService.java
src/main/java/com/app/gradationback/service/ArtServiceImpl.java
src/main/resources/mapper/artMapper.xml

feat: 작품 단일 조회 추가

---

src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/java/com/app/gradationback/service/UserService.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java

feat: ArtPostService 게시 등록 수정

---

src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/controller/FileController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/test/java/com/app/gradationback/mapper/mina/ArtImgMapperTests.java
src/test/java/com/app/gradationback/mapper/mina/ArtMapperTests.java

feat: FileController 수정

---

src/main/java/com/app/gradationback/domain/ArtPostDTO.java

feat: ArtPostDTO 수정

---

src/main/java/com/app/gradationback/controller/UserController.java
src/main/java/com/app/gradationback/mapper/UserMapper.java
src/main/java/com/app/gradationback/repository/UserDAO.java
src/main/java/com/app/gradationback/service/UserService.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java
src/main/resources/mapper/userMapper.xml

feat: userMapper 회원 프로필 이미지 수정 추가

---

src/main/java/com/app/gradationback/controller/FileController.java
src/main/java/com/app/gradationback/domain/DeliveryDTO.java
src/main/java/com/app/gradationback/domain/UserVO.java
src/main/java/com/app/gradationback/mapper/UserMapper.java
src/main/java/com/app/gradationback/repository/UserDAO.java
src/main/java/com/app/gradationback/service/UserService.java
src/main/java/com/app/gradationback/service/UserServiceImpl.java
src/main/resources/mapper/userMapper.xml

feat: UserVO 수정

---

src/main/java/com/app/gradationback/controller/FileController.java
src/main/resources/mapper/userMapper.xml

"feat: fileController 수정"

---

src/main/java/com/app/gradationback/controller/DisplayController.java

feat: DisplayController 단일 조회 수정

---

src/main/java/com/app/gradationback/controller/CommentController.java
src/main/java/com/app/gradationback/controller/UserController.java
src/main/resources/mapper/commentMapper.xml

feat: commentMapper selectKey 추가

---

src/main/java/com/app/gradationback/controller/ArtLikeController.java
src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/domain/ArtPostDTO.java
src/main/java/com/app/gradationback/domain/CommentDTO.java
src/main/java/com/app/gradationback/mapper/ArtMapper.java
src/main/java/com/app/gradationback/mapper/ArtPostMapper.java
src/main/java/com/app/gradationback/repository/ArtDAO.java
src/main/java/com/app/gradationback/repository/ArtPostDAO.java
src/main/java/com/app/gradationback/service/ArtLikeService.java
src/main/java/com/app/gradationback/service/ArtLikeServiceImpl.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/resources/mapper/artMapper.xml
src/main/resources/mapper/artPostMapper.xml
src/main/resources/mapper/commentMapper.xml

feat: ArtLikeController 좋아요 여부 추가

---

src/main/java/com/app/gradationback/controller/UserController.java

feat: 로그인 암호화 조건 수정

---

src/main/java/com/app/gradationback/mapper/MypageMapper.java
src/main/java/com/app/gradationback/repository/MypageDAO.java
src/main/resources/mapper/mypageMapper.xml

feat: mypageMapper 수정

---

src/main/java/com/app/gradationback/controller/CommentController.java
src/main/java/com/app/gradationback/controller/CommentLikeController.java
src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/domain/CommentDTO.java
src/main/java/com/app/gradationback/mapper/CommentMapper.java
src/main/java/com/app/gradationback/repository/CommentDAO.java
src/main/java/com/app/gradationback/service/ArtLikeServiceImpl.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/java/com/app/gradationback/service/CommentLikeService.java
src/main/java/com/app/gradationback/service/CommentLikeServiceImpl.java
src/main/java/com/app/gradationback/service/CommentService.java
src/main/java/com/app/gradationback/service/CommentServiceImpl.java
src/main/resources/mapper/artPostMapper.xml
src/main/resources/mapper/commentMapper.xml

feat: artPostMapper userId 삭제

---

src/main/java/com/app/gradationback/mapper/CommentMapper.java
src/main/java/com/app/gradationback/repository/CommentDAO.java
src/main/java/com/app/gradationback/service/CommentLikeServiceImpl.java
src/main/java/com/app/gradationback/service/CommentService.java
src/main/java/com/app/gradationback/service/CommentServiceImpl.java
src/main/resources/mapper/commentMapper.xml

feat: 댓글 삭제 트랜잭션 추가

---

src/main/resources/mapper/artPostMapper.xml

feat: artPostMapper 작가 상태 수정

---

src/main/java/com/app/gradationback/config/SecurityConfig.java
src/main/java/com/app/gradationback/controller/FileController.java
src/main/java/com/app/gradationback/service/ArtLikeServiceImpl.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/java/com/app/gradationback/util/JwtTokenUtil.java
src/main/resources/mapper/artPostMapper.xml
src/main/resources/mapper/commentMapper.xml

feat: artPostMapper 수정

---

src/main/java/com/app/gradationback/controller/DisplayController.java
src/main/java/com/app/gradationback/mapper/ArtPostMapper.java
src/main/java/com/app/gradationback/repository/ArtPostDAO.java
src/main/java/com/app/gradationback/service/ArtPostService.java
src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java
src/main/resources/mapper/artPostMapper.xml

feat: 메인 리스트 매핑 추가

---

src/main/java/com/app/gradationback/service/ArtPostServiceImpl.java

feat: ArtPostServiceImpl 수정

---

src/main/java/com/app/gradationback/mapper/MypageMapper.java
src/main/java/com/app/gradationback/repository/MypageDAO.java
src/main/resources/mapper/mypageMapper.xml

MypageMapper 수정
